# Generated by Django 4.1.2 on 2022-10-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
