# Generated by Django 4.1.2 on 2022-10-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_like_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='name',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
