# Generated by Django 4.1.1 on 2022-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_like_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=1200),
        ),
    ]
